# Generated by Django 2.2.4 on 2020-05-26 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='added_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_quote', to='quoteapp.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_quote', to='quoteapp.User'),
        ),
    ]
