# Generated by Django 2.2.4 on 2020-05-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0002_auto_20200526_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='massage',
            new_name='message',
        ),
    ]
